version: "3"

services:
  project:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: 'bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy

  celery:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: 'celery -A online_school worker -l info -P eventlet'
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq

  mysql_db:
    image: mysql:5.7.8
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 100