# Generated by Django 4.1.1 on 2022-10-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coursetheses_course_theses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetheses',
            name='course_theses',
        ),
    ]
