# Generated by Django 4.1.1 on 2022-11-05 21:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_created_at_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.course_upload_path),
        ),
    ]
